name: build docker
on: [push]
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.org_docker_password }} | docker login --username ${{ secrets.org_docker_username }} --password-stdin

    # Build images
    - name: INFO BUILD
      run: echo ${{ github.event.inputs.path }} ${{ github.event.inputs.image }} ${{ github.event.inputs.version }}
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})        
    - name: build an image
      run: docker build . --file Dockerfile --tag blocknetdx/exrproxy:${{steps.vars.outputs.tag}}
    - name: push image
      run: docker push blocknetdx/exrproxy:${{steps.vars.outputs.tag}}
    - name: build an image
      run: docker build . --file Dockerfile --tag blocknetdx/exrproxy:latest
    - name: push image
      run: docker push blocknetdx/exrproxy:latest
    - name: Remove dangling images
      if: ${{ always() }}
      run: yes | docker image prune
    - name: Push an image to DockerHub
      run: ./ci.sh push "${{ github.event.inputs.image }}" "${{ github.event.inputs.version }}" "*" "${{ github.event.inputs.repo }}"
